
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        # generaric test
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: completed_orders
    description: "completed orders with first name and last name"
    columns:
      - name: id 
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['completed']